name: Run CI build

on:
  pullrequest:
    branches: ['main']

# Allow one concurrent deployment
concurrency:
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          CI: true